name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: arc-runner-portfolio
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install buildah
        run: sudo apt-get install -y buildah

      - name: Build and push
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          buildah build -t ghcr.io/${{ github.repository }}:${SHORT_SHA} .

          if [ "${{ github.event_name }}" != "pull_request" ]; then
            buildah tag \
              ghcr.io/${{ github.repository }}:${SHORT_SHA} \
              ghcr.io/${{ github.repository }}:main

            buildah push \
              --creds "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" \
              ghcr.io/${{ github.repository }}:${SHORT_SHA}

            buildah push \
              --creds "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" \
              ghcr.io/${{ github.repository }}:main
          fi
