name: First workflow to print Dockerfile

on:
  - push

jobs:
  ReadDockerfile:
    runs-on: arc-runner-portfolio
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: install cowsay
        run: |
          ls -al
          cat Dockerfile
          cat /etc/*release*
          sudo apt-get update
          sudo apt-get install -y cowsay
          cowsay -f dragon "hello, world"
      - name: Dragon say hello
        run: cowsay -f dragon "hello, world"
