name: First workflow to print Dockerfile

on:
  - push

jobs:
  ReadDockerfile:
    runs-on: arc-runner-portfolio
    steps:
      - name: Starting job Read Dockerfile
        run: echo "Starting Job Read Dockerfile"

      - name: Checkout repo
        uses: actions/checkout@v6

      - name: List the files
        run: ls -al

      - name: Read DockerFile
        run: cat Dockerfile
  Anotherjob:
    runs-on: arc-runner-portfolio
    steps:
      - name: Read Readme file
        run: cat README.md
